const articleslist = [
  {
    title: "9 fascinating things about christmans",
    program: "case study",
    image: "/globaladmissions/images/articles/p1.png",
    author: "Christine Chiu",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "case-study",
  },
  {
    title: "9 fascinating things about christmans",
    program: "programs",
    image: "/globaladmissions/images/articles/p2.png",
    author: "Christine Chiu",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "programs",
  },
  {
    title: "9 fascinating things about christmans",
    program: "case study",
    image: "/globaladmissions/images/articles/p1.png",
    author: "Christine Chiu",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "case-study",
  },
  {
    title: "9 fascinating things about christmans",
    program: "programs",
    image: "/globaladmissions/images/articles/p2.png",
    author: "Christine Chiu",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "programs",
  },
  {
    title: "9 fascinating things about christmans",
    program: "case study",
    image: "/globaladmissions/images/articles/p1.png",
    author: "Christine Chiu",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "case-study",
  },
  {
    title: "9 fascinating things about christmans",
    program: "programs",
    image: "/globaladmissions/images/articles/p2.png",
    author: "Christine Chiu",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "programs",
  },
];

export default articleslist;
