const lessnewslist = [
  {
    title: "Join our WeChat group for student updates!",
    program: "case study",
    image: "/globaladmissions/images/news/n1.png",
    authorImg: "/globaladmissions/images/news/ln1.png",
    author: "Savanna Billman",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "case-study",
  },
  {
    title: "How to Say 10 Winter Holidays in Chinese",
    program: "programs",
    image: "/globaladmissions/images/news/n2.png",
    authorImg: "/globaladmissions/images/news/ln2.png",
    author: "Zi Parrish",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "programs",
  },
  {
    title: "FAQ: Can you study in China even if you have low grades?",
    program: "MBBS",
    image: "/globaladmissions/images/news/n3.png",
    authorImg: "/globaladmissions/images/news/ln3.png",
    author: "Giorgio Cleveland",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "mbbs",
  },
  {
    title: "FAQ: Can you study in China even if you have low grades?",
    program: "MBBS",
    image: "/globaladmissions/images/news/n4.png",
    authorImg: "/globaladmissions/images/news/ln4.png",
    author: "Giorgio Cleveland",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "mbbs",
  },
  {
    title: "FAQ: Can you study in China even if you have low grades?",
    program: "MBBS",
    image: "/globaladmissions/images/news/n5.png",
    authorImg: "/globaladmissions/images/news/ln5.png",
    author: "Giorgio Cleveland",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "mbbs",
  },
  {
    title: "FAQ: Can you study in China even if you have low grades?",
    program: "MBBS",
    image: "/globaladmissions/images/news/n6.png",
    authorImg: "/globaladmissions/images/news/ln6.png",
    author: "Giorgio Cleveland",
    date: "Nov 24, 2022",
    length: "8 min read",
    blogItem: "mbbs",
  },
];

export default lessnewslist;
